package model.pojo;
// Generated 11/12/2019 11:28:16 AM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private int coste;
     private String nombre;

    public Categoria() {
    }

    public Categoria(int coste, String nombre) {
       this.coste = coste;
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCoste() {
        return this.coste;
    }
    
    public void setCoste(int coste) {
        this.coste = coste;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


